# Generated by Django 4.2.10 on 2024-05-31 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado_actual', models.CharField(choices=[('1', 'Nuevo'), ('2', 'En Progreso'), ('3', 'En Revisión'), ('4', 'Completado')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='profiles/LogoAic2.jpeg', null=True, upload_to='profiles', verbose_name='Avatar')),
                ('tipdoc', models.CharField(choices=[('CC', 'CÉDULA DE CIUDADANIA'), ('CE', 'CÉDULA DE EXTRANJERIA'), ('CD', 'CARNET DIPLOMATICO'), ('PS', 'PASAPORTE')], max_length=2, verbose_name='Tipo de documento')),
                ('identificacion', models.BigIntegerField(blank=True, null=True, verbose_name='Nr° identificación')),
                ('pnombre', models.CharField(max_length=60, verbose_name='Primer nombre')),
                ('snombre', models.CharField(blank=True, max_length=60, null=True, verbose_name='Segundo nombre')),
                ('papellido', models.CharField(max_length=60, verbose_name='Primer apellido')),
                ('sapellido', models.CharField(blank=True, max_length=60, null=True, verbose_name='Segundo apellido')),
                ('fecexped', models.DateField(blank=True, null=True, verbose_name='Fecha de Expedición')),
                ('lugarexpe', models.CharField(blank=True, max_length=60, null=True, verbose_name='Lugar de Expedición')),
                ('fechanac', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('lugarnac', models.CharField(blank=True, max_length=60, null=True, verbose_name='Lugar de Nacimiento')),
                ('correo', models.CharField(blank=True, max_length=60, null=True, verbose_name='Correo Electronico')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('celular', models.BigIntegerField(blank=True, null=True, verbose_name='Celular')),
                ('proceso', models.CharField(choices=[('AP', 'ADMINISTRACIÓN Y PLANEACIÓN'), ('AO', 'APOYO ORGANIZATIVO Y SOCIOCULTURAL'), ('AS', 'ASEGURAMIENTO'), ('AC', 'ATENCION AL COMUNERO'), ('CI', 'CONTROL INTERNO'), ('FI', 'FINANCIERA'), ('GC', 'GARANTIA DE LA CALIDAD'), ('JU', 'JURIDICA'), ('MI', 'MINGA'), ('PR', 'PRESTADOR'), ('PO', 'PROVEEDOR'), ('GT', 'GESTION TIC'), ('RP', 'REPORTES'), ('NA', 'NO APLICA')], default='NA', max_length=2, verbose_name='Proceso')),
                ('rol', models.CharField(choices=[('RSC', 'REGISTRO SOLICITUD DE COTIZACIONES'), ('PMD', 'PERTINENCIA MEDICA'), ('ASE', 'GESTION ASEGURAMIENTO'), ('SGH', 'SEGUIMIENTO HOSPITALARIO'), ('COV', 'SEGUIMIENTO COVID'), ('API', 'SERVICE WEB'), ('NTRL', 'PERSONA NATURAL'), ('JDCA', 'PERSONA JURIDICA'), ('ALT', 'ALTO COSTO'), ('RPT', 'REPORTES AIC EPSI'), ('GES', 'GESTANTES'), ('NA', 'NO APLICA')], default='NA', max_length=4, verbose_name='Rol')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
